#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from part1-1.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "part1-1.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct node
{
	char *token;
	struct node *left;
	struct node *right;
} node;

node* mknode(char *token, node *left, node *right);
void printTree(node *tree);

void printSpace(int n);

int yylex();
int yyerror(char *e);
int spaces=0;

#line 23 "part1-1.y"
typedef union
{
    struct node *node;
    char *string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	COMMENT	258
#define	LENGTH	259
#define	BOOL	260
#define	INT	261
#define	REAL	262
#define	STRING	263
#define	CHAR	264
#define	VAR	265
#define	ARG	266
#define	INTPTR	267
#define	CHARPTR	268
#define	REALPTR	269
#define	IF	270
#define	ELSE	271
#define	DO	272
#define	WHILE	273
#define	FOR	274
#define	FUNC	275
#define	VOID	276
#define	RETURN	277
#define	AND	278
#define	OR	279
#define	EQ	280
#define	GTE	281
#define	LTE	282
#define	NOTEQ	283
#define	NOT	284
#define	GT	285
#define	LT	286
#define	ASS	287
#define	ID	288
#define	STR_VAL	289
#define	REAL_VAL	290
#define	CHAR_VAL	291
#define	NUL	292
#define	DEC_VAL	293
#define	HEX_VAL	294
#define	BOOLVAL	295


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int COMMENT;
static const int LENGTH;
static const int BOOL;
static const int INT;
static const int REAL;
static const int STRING;
static const int CHAR;
static const int VAR;
static const int ARG;
static const int INTPTR;
static const int CHARPTR;
static const int REALPTR;
static const int IF;
static const int ELSE;
static const int DO;
static const int WHILE;
static const int FOR;
static const int FUNC;
static const int VOID;
static const int RETURN;
static const int AND;
static const int OR;
static const int EQ;
static const int GTE;
static const int LTE;
static const int NOTEQ;
static const int NOT;
static const int GT;
static const int LT;
static const int ASS;
static const int ID;
static const int STR_VAL;
static const int REAL_VAL;
static const int CHAR_VAL;
static const int NUL;
static const int DEC_VAL;
static const int HEX_VAL;
static const int BOOLVAL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,COMMENT=258
	,LENGTH=259
	,BOOL=260
	,INT=261
	,REAL=262
	,STRING=263
	,CHAR=264
	,VAR=265
	,ARG=266
	,INTPTR=267
	,CHARPTR=268
	,REALPTR=269
	,IF=270
	,ELSE=271
	,DO=272
	,WHILE=273
	,FOR=274
	,FUNC=275
	,VOID=276
	,RETURN=277
	,AND=278
	,OR=279
	,EQ=280
	,GTE=281
	,LTE=282
	,NOTEQ=283
	,NOT=284
	,GT=285
	,LT=286
	,ASS=287
	,ID=288
	,STR_VAL=289
	,REAL_VAL=290
	,CHAR_VAL=291
	,NUL=292
	,DEC_VAL=293
	,HEX_VAL=294
	,BOOLVAL=295


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::COMMENT=258;
const int YY_parse_CLASS::LENGTH=259;
const int YY_parse_CLASS::BOOL=260;
const int YY_parse_CLASS::INT=261;
const int YY_parse_CLASS::REAL=262;
const int YY_parse_CLASS::STRING=263;
const int YY_parse_CLASS::CHAR=264;
const int YY_parse_CLASS::VAR=265;
const int YY_parse_CLASS::ARG=266;
const int YY_parse_CLASS::INTPTR=267;
const int YY_parse_CLASS::CHARPTR=268;
const int YY_parse_CLASS::REALPTR=269;
const int YY_parse_CLASS::IF=270;
const int YY_parse_CLASS::ELSE=271;
const int YY_parse_CLASS::DO=272;
const int YY_parse_CLASS::WHILE=273;
const int YY_parse_CLASS::FOR=274;
const int YY_parse_CLASS::FUNC=275;
const int YY_parse_CLASS::VOID=276;
const int YY_parse_CLASS::RETURN=277;
const int YY_parse_CLASS::AND=278;
const int YY_parse_CLASS::OR=279;
const int YY_parse_CLASS::EQ=280;
const int YY_parse_CLASS::GTE=281;
const int YY_parse_CLASS::LTE=282;
const int YY_parse_CLASS::NOTEQ=283;
const int YY_parse_CLASS::NOT=284;
const int YY_parse_CLASS::GT=285;
const int YY_parse_CLASS::LT=286;
const int YY_parse_CLASS::ASS=287;
const int YY_parse_CLASS::ID=288;
const int YY_parse_CLASS::STR_VAL=289;
const int YY_parse_CLASS::REAL_VAL=290;
const int YY_parse_CLASS::CHAR_VAL=291;
const int YY_parse_CLASS::NUL=292;
const int YY_parse_CLASS::DEC_VAL=293;
const int YY_parse_CLASS::HEX_VAL=294;
const int YY_parse_CLASS::BOOLVAL=295;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		199
#define	YYFLAG		-32768
#define	YYNTBASE	53

#define YYTRANSLATE(x) ((unsigned)(x) <= 295 ? yytranslate[x] : 93)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    41,
    42,    51,    49,    47,    50,     2,    52,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    43,    46,     2,
    48,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    44,     2,    45,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     7,     9,    12,    13,    21,    26,    31,
    34,    35,    39,    40,    46,    50,    51,    53,    55,    57,
    59,    61,    63,    65,    67,    73,    76,    77,    81,    82,
    90,    95,    96,    99,   100,   104,   106,   108,   110,   114,
   116,   118,   120,   122,   124,   126,   128,   130,   132,   134,
   136,   138,   140,   152,   156,   158,   160,   165,   168,   173,
   175,   176,   179,   181,   185,   189,   190,   192,   194,   196,
   198,   200,   202,   204,   206,   208,   211,   214,   217,   221,
   225,   229,   231,   233,   241,   250,   259,   263,   264,   267,
   270,   273,   276,   279,   282,   287,   288,   292,   294,   296,
   298
};

static const short yyrhs[] = {    54,
    55,     0,     3,    54,     0,     0,    56,     0,    57,    56,
     0,     0,    20,    33,    41,    59,    42,    43,    58,     0,
    63,    44,    91,    45,     0,    21,    44,    89,    45,     0,
    61,    60,     0,     0,    46,    61,    60,     0,     0,    11,
    33,    62,    43,    63,     0,    47,    33,    62,     0,     0,
     6,     0,     7,     0,     5,     0,     8,     0,     9,     0,
    12,     0,    13,     0,    14,     0,    33,    41,    65,    42,
    46,     0,    33,    66,     0,     0,    47,    33,    66,     0,
     0,    10,    33,    69,    68,    43,    63,    46,     0,    47,
    33,    69,    68,     0,     0,    48,    70,     0,     0,    41,
    70,    42,     0,    72,     0,    33,     0,    64,     0,    70,
    71,    70,     0,    49,     0,    50,     0,    51,     0,    52,
     0,    34,     0,    35,     0,    36,     0,    38,     0,    39,
     0,    40,     0,    74,     0,    85,     0,    86,     0,    19,
    41,    75,    46,    77,    46,    82,    42,    44,    84,    45,
     0,    33,    48,    76,     0,    38,     0,    33,     0,    41,
    77,    42,    80,     0,    78,    80,     0,    70,    81,    70,
    80,     0,    29,     0,     0,    29,    79,     0,    70,     0,
    41,    77,    42,     0,    81,    77,    80,     0,     0,    25,
     0,    26,     0,    27,     0,    28,     0,    30,     0,    31,
     0,    23,     0,    24,     0,    32,     0,    33,    83,     0,
    49,    49,     0,    50,    50,     0,    51,    48,    38,     0,
    49,    48,    38,     0,    50,    48,    38,     0,    89,     0,
    91,     0,    18,    41,    77,    42,    44,    84,    45,     0,
    17,    44,    84,    45,    18,    41,    77,    42,     0,    15,
    41,    77,    42,    44,    84,    45,    88,     0,    44,    84,
    45,     0,     0,    54,    90,     0,    57,    89,     0,    87,
    89,     0,    67,    89,     0,    73,    89,     0,    64,    89,
     0,    44,    89,    45,    89,     0,     0,    89,    22,    92,
     0,    33,     0,    64,     0,    72,     0,    77,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    98,   101,   101,   104,   108,   109,   112,   121,   132,   146,
   149,   157,   158,   161,   167,   168,   171,   171,   172,   173,
   174,   175,   176,   177,   181,   192,   194,   197,   198,   201,
   214,   220,   223,   223,   226,   226,   227,   228,   229,   238,
   238,   239,   240,   244,   244,   245,   246,   247,   248,   253,
   253,   254,   257,   300,   306,   306,   309,   309,   310,   322,
   322,   325,   328,   328,   333,   339,   342,   342,   343,   344,
   345,   346,   347,   348,   349,   355,   360,   360,   361,   362,
   363,   367,   367,   371,   383,   397,   409,   412,   416,   418,
   418,   419,   420,   421,   422,   426,   429,   436,   436,   437,
   438
};

static const char * const yytname[] = {   "$","error","$illegal.","COMMENT",
"LENGTH","BOOL","INT","REAL","STRING","CHAR","VAR","ARG","INTPTR","CHARPTR",
"REALPTR","IF","ELSE","DO","WHILE","FOR","FUNC","VOID","RETURN","AND","OR","EQ",
"GTE","LTE","NOTEQ","NOT","GT","LT","ASS","ID","STR_VAL","REAL_VAL","CHAR_VAL",
"NUL","DEC_VAL","HEX_VAL","BOOLVAL","'('","')'","':'","'{'","'}'","';'","','",
"'='","'+'","'-'","'*'","'/'","project","cmt","program","processes","process",
"prosSplit","args","argss","arg","ids","type","funccall","funcargs","moreargs",
"vardic","varsdic","varasign","ex","op","val","lop","forlop","init","intval",
"expression","notexp","splitnot","lopexp","oper","update","updatechage","lopbody",
"whilelop","dolop","ifstate","elstate","body","bodysplit","bodyret","retval",
"retval"
};
#endif

static const short yyr1[] = {     0,
    53,    54,    54,    55,    56,    56,    57,    58,    58,    59,
    59,    60,    60,    61,    62,    62,    63,    63,    63,    63,
    63,    63,    63,    63,    64,    65,    65,    66,    66,    67,
    68,    68,    69,    69,    70,    70,    70,    70,    70,    71,
    71,    71,    71,    72,    72,    72,    72,    72,    72,    73,
    73,    73,    74,    75,    76,    76,    77,    77,    77,    -1,
    -1,    78,    79,    79,    80,    80,    81,    81,    81,    81,
    81,    81,    81,    81,    81,    82,    83,    83,    83,    83,
    83,    84,    84,    85,    86,    87,    88,    88,    89,    90,
    90,    90,    90,    90,    90,    90,    91,    92,    92,    92,
    92
};

static const short yyr2[] = {     0,
     2,     2,     0,     1,     2,     0,     7,     4,     4,     2,
     0,     3,     0,     5,     3,     0,     1,     1,     1,     1,
     1,     1,     1,     1,     5,     2,     0,     3,     0,     7,
     4,     0,     2,     0,     3,     1,     1,     1,     3,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,    11,     3,     1,     1,     4,     2,     4,     1,
     0,     2,     1,     3,     3,     0,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     2,     2,     2,     3,     3,
     3,     1,     1,     7,     8,     8,     3,     0,     2,     2,
     2,     2,     2,     2,     4,     0,     3,     1,     1,     1,
     1
};

static const short yydefact[] = {     3,
     3,     6,     2,     0,     1,     4,     6,     0,     5,    11,
     0,     0,    13,    16,     0,     0,    10,     0,     0,     0,
    13,    16,     0,    19,    17,    18,    20,    21,    22,    23,
    24,     0,     7,     0,    12,    15,    14,     3,     3,    96,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     3,
     3,     3,     3,     3,    50,    51,    52,     3,    89,     9,
     0,     8,    34,     0,     3,     0,     0,    27,     0,    90,
    94,    92,    93,    91,     0,    37,    44,    45,    46,    47,
    48,    49,     0,    38,     0,    36,   101,    66,    97,     0,
    32,    37,    38,    36,     0,     0,    82,    83,     0,     0,
     0,    29,     0,     3,     0,    63,    62,     0,     0,    73,
    74,    67,    68,    69,    70,    71,    72,    75,    40,    41,
    42,    43,     0,     0,    58,     0,     0,    33,     0,     0,
     0,     0,     0,     0,     0,     0,    26,     0,    95,     0,
    35,    66,    39,    66,    66,     0,    34,     0,     3,     0,
     3,    56,    55,    54,     0,    29,    25,    64,    57,    59,
    65,    32,     0,     0,     0,     0,     0,    28,    31,    30,
    88,     0,    84,     0,     0,     3,    86,    85,     0,     0,
     0,    76,     0,     0,     0,    77,     0,    78,     0,     3,
    87,    80,    81,    79,     0,    53,     0,     0,     0
};

static const short yydefgoto[] = {   197,
    40,     5,     6,     7,    33,    12,    17,    13,    19,    34,
    93,   103,   137,    53,   130,    91,    85,   123,    94,    54,
    55,   101,   154,    87,    88,   107,   125,   126,   175,   182,
    96,    56,    57,    58,   177,    97,    59,    98,    89
};

static const short yypact[] = {    -1,
    -1,    10,-32768,   -15,-32768,-32768,    10,     4,-32768,    15,
    34,    -3,    37,    53,    58,    15,-32768,    78,    77,    52,
    37,    53,   153,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    79,-32768,    80,-32768,-32768,-32768,    -1,    -1,    18,
    76,   108,    91,   104,    97,    99,   113,   122,   123,    -1,
    -1,    -1,    -1,    -1,-32768,-32768,-32768,    -1,-32768,-32768,
    93,-32768,   124,   106,    -1,   106,   144,   145,   134,-32768,
-32768,-32768,-32768,-32768,    74,   -28,-32768,-32768,-32768,-32768,
-32768,-32768,   106,   136,    67,   137,-32768,   125,-32768,   135,
   133,   123,-32768,-32768,   141,   139,   108,-32768,   143,   138,
   142,   140,   147,    -1,   106,    19,-32768,    54,   148,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   135,   135,-32768,   106,   135,    19,   158,   149,
   150,   175,   151,   -22,   106,   163,-32768,   152,-32768,   155,
-32768,   125,    19,    67,   125,    -2,   124,   153,    -1,   159,
    -1,-32768,-32768,-32768,   156,   140,-32768,-32768,-32768,-32768,
-32768,   133,   157,   154,   106,   160,   168,-32768,-32768,-32768,
   162,   165,-32768,    38,   166,    -1,-32768,-32768,     6,    26,
   161,-32768,   167,   169,   172,-32768,   174,-32768,   177,    -1,
-32768,-32768,-32768,-32768,   171,-32768,   204,   213,-32768
};

static const short yypgoto[] = {-32768,
    14,-32768,   210,   178,-32768,-32768,   198,   205,   200,   -23,
   -34,-32768,    64,-32768,    61,    81,   -71,-32768,   164,-32768,
-32768,-32768,-32768,   -63,-32768,-32768,  -101,   -77,-32768,-32768,
  -144,-32768,-32768,-32768,-32768,   -29,-32768,   185,-32768
};


#define	YYLAST		228


static const short yytable[] = {    37,
    95,     1,    99,   106,   164,    52,   166,   124,    41,    42,
   152,   108,    68,     2,     3,   153,   -98,     8,   128,   109,
    69,    70,    71,    72,    73,    11,    84,    44,    74,     4,
   124,   184,    45,   108,    46,    47,    48,     4,    15,   141,
   159,   140,   160,   161,    10,   195,   119,   120,   121,   122,
    49,   143,   144,   185,   186,   146,    24,    25,    26,    27,
    28,    50,   145,    29,    30,    31,    14,   119,   120,   121,
   122,   155,    32,   187,   139,   188,   110,   111,   112,   113,
   114,   115,    16,   116,   117,   118,   179,   180,   181,   110,
   111,   112,   113,   114,   115,   141,   116,   117,   118,    18,
    20,   172,   119,   120,   121,   122,    92,    77,    78,    79,
    22,    80,    81,    82,   105,   119,   120,   121,   122,    23,
    60,    75,    38,    39,   163,    76,    77,    78,    79,    61,
    80,    81,    82,    83,    75,    62,    63,    64,    92,    77,
    78,    79,    65,    80,    81,    82,    83,   110,   111,   112,
   113,   114,   115,    66,   116,   117,   118,    24,    25,    26,
    27,    28,    67,    68,    29,    30,    31,    92,    77,    78,
    79,    90,    80,    81,    82,   127,   100,   102,   104,   129,
   -99,  -100,   131,   132,   133,   134,   136,   135,   138,   142,
   147,   148,   150,   149,   151,   156,   158,   157,   171,   165,
   174,   167,   170,   198,   173,   176,   178,   183,   189,   192,
   190,   193,   199,   191,   194,   196,     9,    51,    35,   168,
    21,    36,   169,    43,    86,     0,     0,   162
};

static const short yycheck[] = {    23,
    64,     3,    66,    75,   149,    40,   151,    85,    38,    39,
    33,    83,    41,     0,     1,    38,    45,    33,    90,    83,
    50,    51,    52,    53,    54,    11,    61,    10,    58,    20,
   108,   176,    15,   105,    17,    18,    19,    20,    42,    42,
   142,   105,   144,   145,    41,   190,    49,    50,    51,    52,
    33,   123,   124,    48,    49,   127,     5,     6,     7,     8,
     9,    44,   126,    12,    13,    14,    33,    49,    50,    51,
    52,   135,    21,    48,   104,    50,    23,    24,    25,    26,
    27,    28,    46,    30,    31,    32,    49,    50,    51,    23,
    24,    25,    26,    27,    28,    42,    30,    31,    32,    47,
    43,   165,    49,    50,    51,    52,    33,    34,    35,    36,
    33,    38,    39,    40,    41,    49,    50,    51,    52,    43,
    45,    29,    44,    44,   148,    33,    34,    35,    36,    22,
    38,    39,    40,    41,    29,    45,    33,    41,    33,    34,
    35,    36,    44,    38,    39,    40,    41,    23,    24,    25,
    26,    27,    28,    41,    30,    31,    32,     5,     6,     7,
     8,     9,    41,    41,    12,    13,    14,    33,    34,    35,
    36,    48,    38,    39,    40,    41,    33,    33,    45,    47,
    45,    45,    42,    45,    42,    48,    47,    46,    42,    42,
    33,    43,    18,    44,    44,    33,    42,    46,    45,    41,
    33,    46,    46,     0,    45,    44,    42,    42,    48,    38,
    44,    38,     0,    45,    38,    45,     7,    40,    21,   156,
    16,    22,   162,    39,    61,    -1,    -1,   147
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 98 "part1-1.y"
{printTree(yyvsp[-1].string);;
    break;}
case 4:
#line 104 "part1-1.y"
{yyval.node=mknode("CODE",yyvsp[0].node,mknode(")",NULL,NULL));;
    break;}
case 5:
#line 108 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,yyvsp[0].node);;
    break;}
case 6:
#line 109 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 7:
#line 114 "part1-1.y"
{yyval.node=mknode("FUNC",
															mknode("PRINT_TOKEN",
																	mknode(yyvsp[-5].string,NULL,NULL),
																	mknode("\n",yyvsp[-3].node,yyvsp[0].node)),				
															mknode(")",NULL,NULL));;
    break;}
case 8:
#line 123 "part1-1.y"
{yyval.node=mknode("\n",
												mknode("RET",
														mknode("PRINT_TOKEN",yyvsp[-3].node,NULL),
														mknode(")",NULL,NULL)),
												mknode("\n",
															mknode("BODY",
																		yyvsp[-1].node,
																		mknode(")",NULL,NULL)),NULL));;
    break;}
case 9:
#line 134 "part1-1.y"
{yyval.node=mknode("\n",
											mknode("RET",
													mknode("PRINT_TOKEN",mknode("VOID",NULL,NULL),NULL),
													mknode(")",NULL,NULL)),
											mknode("\n",
														mknode("BODY",
																	yyvsp[-1].node,
																	mknode(")",NULL,NULL)),NULL));;
    break;}
case 10:
#line 146 "part1-1.y"
{yyval.node=mknode("ARGS",
								mknode("",yyvsp[-1].node,yyvsp[0].node),
								mknode(")",NULL,NULL));;
    break;}
case 11:
#line 149 "part1-1.y"
{yyval.node=mknode("ARGS",
								mknode("PRINT_TOKEN",
													mknode("NONE",NULL,NULL),
													NULL),
								mknode(")",NULL,NULL));;
    break;}
case 12:
#line 157 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,NULL);;
    break;}
case 13:
#line 158 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 14:
#line 161 "part1-1.y"
{yyval.node=mknode("",
										yyvsp[0].node,
										mknode("PRINT_TOKEN",
															mknode(yyvsp[-3].string,yyvsp[-2].node,NULL),NULL));;
    break;}
case 15:
#line 167 "part1-1.y"
{yyval.node=mknode("PRINT_TOKEN",mknode(yyvsp[-1].string,yyvsp[0].node,NULL),NULL);;
    break;}
case 16:
#line 168 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 17:
#line 171 "part1-1.y"
{yyval.node=mknode("INT",NULL,NULL);;
    break;}
case 18:
#line 172 "part1-1.y"
{yyval.node=mknode("REAL",NULL,NULL);;
    break;}
case 19:
#line 173 "part1-1.y"
{yyval.node=mknode("BOOL",NULL,NULL);;
    break;}
case 20:
#line 174 "part1-1.y"
{yyval.node=mknode("STRING",NULL,NULL);;
    break;}
case 21:
#line 175 "part1-1.y"
{yyval.node=mknode("CHAR",NULL,NULL);;
    break;}
case 22:
#line 176 "part1-1.y"
{yyval.node=mknode("INTPTR",NULL,NULL);;
    break;}
case 23:
#line 177 "part1-1.y"
{yyval.node=mknode("CHARPTR",NULL,NULL);;
    break;}
case 24:
#line 178 "part1-1.y"
{yyval.node=mknode("REALPTR",NULL,NULL);;
    break;}
case 25:
#line 183 "part1-1.y"
{yyval.node=mknode("CALL FUNC", 
													mknode("PRINT_TOKEN",
																		mknode(yyvsp[-4].string,mknode("\n",NULL,NULL),NULL),
																		mknode("PARAMS",
																						yyvsp[-2].node,
																						mknode(")",NULL,NULL))
																						),NULL);;
    break;}
case 26:
#line 193 "part1-1.y"
{yyval.node=mknode("PRINT_TOKEN",mknode(yyvsp[-1].string,NULL,NULL),yyvsp[0].node);;
    break;}
case 27:
#line 194 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 28:
#line 197 "part1-1.y"
{yyval.node=mknode("PRINT_TOKEN",mknode(yyvsp[-1].string,NULL,NULL),yyvsp[0].node);;
    break;}
case 29:
#line 198 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 30:
#line 202 "part1-1.y"
{yyval.node=mknode("DECLARATION",
												yyvsp[-1].node,
												mknode("\n",
															mknode("=",
																		yyvsp[-4].node,
																		mknode(yyvsp[-5].string,
																					yyvsp[-3].node,
																					mknode(")",NULL,NULL))),
															NULL));;
    break;}
case 31:
#line 215 "part1-1.y"
{yyval.node=mknode("=",
													yyvsp[-1].node,
													mknode(yyvsp[-2].string,
																yyvsp[0].node,
																mknode(")",NULL,NULL)));;
    break;}
case 32:
#line 220 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 33:
#line 223 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 34:
#line 223 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 35:
#line 226 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,NULL);
    break;}
case 36:
#line 227 "part1-1.y"
{yyval.node=mknode("PRINT_TOKEN",yyvsp[0].node,NULL);;
    break;}
case 37:
#line 228 "part1-1.y"
{yyval.node=mknode("PRINT_TOKEN",mknode(yyvsp[0].string,NULL,NULL),NULL);;
    break;}
case 38:
#line 229 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 39:
#line 231 "part1-1.y"
{yyval.node=mknode("OPERATION",
										mknode("PRINT_TOKEN",
															yyvsp[-1].node,
															mknode("",yyvsp[-2].node,yyvsp[0].node)),
										mknode(")",NULL,NULL)) ;;
    break;}
case 40:
#line 238 "part1-1.y"
{yyval.node=mknode("+",NULL,NULL);;
    break;}
case 41:
#line 239 "part1-1.y"
{yyval.node=mknode("-",NULL,NULL);;
    break;}
case 42:
#line 240 "part1-1.y"
{yyval.node=mknode("*",NULL,NULL);;
    break;}
case 43:
#line 241 "part1-1.y"
{yyval.node=mknode("/",NULL,NULL);;
    break;}
case 44:
#line 244 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);
    break;}
case 45:
#line 245 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);
    break;}
case 46:
#line 246 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);
    break;}
case 47:
#line 247 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);
    break;}
case 48:
#line 248 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);
    break;}
case 49:
#line 249 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);
    break;}
case 50:
#line 253 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);
    break;}
case 51:
#line 254 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);
    break;}
case 52:
#line 255 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);
    break;}
case 53:
#line 275 "part1-1.y"
{
		yyval.node=mknode("FOR" ,
						mknode("INIT" ,
										mknode("",
												yyvsp[-8].node,
												mknode("\n",
															mknode("EXPRESSION" ,
																				yyvsp[-6].node,
																				mknode(")",NULL,NULL)),
															mknode("\n",
																		mknode("UPDATE",
																						yyvsp[-4].node,
																						mknode(")",NULL,NULL)),
																		mknode("\n",
																					mknode("{}",
																								yyvsp[-1].node,
																								NULL),
																					NULL)))),
										mknode(")" , NULL,NULL)),
						mknode(")",NULL,NULL));
						
									
	;
    break;}
case 54:
#line 300 "part1-1.y"
{yyval.node = mknode("=",
									mknode("",
												yyvsp[0].node,
												mknode(")",NULL,NULL)),
									mknode(yyvsp[-2].string,NULL,NULL));;
    break;}
case 55:
#line 306 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 56:
#line 307 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 57:
#line 309 "part1-1.y"
{yyval.node=mknode("(",yyvsp[-2].node,yyvsp[0].node);;
    break;}
case 58:
#line 310 "part1-1.y"
{yyval.node=mknode(" ",yyvsp[-1].node,yyvsp[0].node);;
    break;}
case 59:
#line 311 "part1-1.y"
{yyval.node=mknode("OPERATION",
																mknode("",
																			yyvsp[-2].node,
																			mknode("",
																						yyvsp[-3].node,
																						mknode("",
																									yyvsp[-1].node,
																									NULL))),
																mknode(")",NULL,NULL));;
    break;}
case 60:
#line 322 "part1-1.y"
{yyval.node = mknode(yyvsp[0].string,NULL,NULL);
    break;}
case 61:
#line 322 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 62:
#line 325 "part1-1.y"
{yyval.node=mknode("PRINT_TOKEN",mknode(yyvsp[-1].string,yyvsp[0].node,NULL),NULL);;
    break;}
case 63:
#line 328 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 64:
#line 329 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,NULL);;
    break;}
case 65:
#line 334 "part1-1.y"
{yyval.node=mknode("OPERATION",
														mknode("",
																	yyvsp[-1].node,
																	mknode("",yyvsp[-2].node,yyvsp[0].node)),
														mknode(")",NULL,NULL)) ;;
    break;}
case 66:
#line 339 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 67:
#line 342 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 68:
#line 343 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 69:
#line 344 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 70:
#line 345 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 71:
#line 346 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 72:
#line 347 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 73:
#line 348 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 74:
#line 349 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 75:
#line 350 "part1-1.y"
{yyval.node=mknode(yyvsp[0].string,NULL,NULL);;
    break;}
case 76:
#line 355 "part1-1.y"
{yyval.node=mknode("UPDATE",
										mknode("PRINT_TOKEN",yyvsp[0].node,NULL),
										mknode(")",NULL,NULL));;
    break;}
case 77:
#line 360 "part1-1.y"
{yyval.node=mknode("+1",NULL,NULL);;
    break;}
case 78:
#line 361 "part1-1.y"
{yyval.node=mknode("-1",NULL,NULL);;
    break;}
case 79:
#line 362 "part1-1.y"
{yyval.node=mknode("*",yyvsp[0].string,NULL);;
    break;}
case 80:
#line 363 "part1-1.y"
{yyval.node=mknode("+",yyvsp[0].string,NULL);;
    break;}
case 81:
#line 364 "part1-1.y"
{yyval.node=mknode("-",yyvsp[0].string,NULL);;
    break;}
case 82:
#line 367 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 83:
#line 368 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 84:
#line 372 "part1-1.y"
{yyval.node=mknode("WHILE",
								mknode("EXPRESSION",
													mknode("",
																yyvsp[-4].node,
																mknode("{}",
																			yyvsp[-1].node,
																			mknode(")",NULL,NULL))),
													mknode(")",NULL,NULL)),
								mknode(")",NULL,NULL));;
    break;}
case 85:
#line 384 "part1-1.y"
{yyval.node=mknode("DO-WHILE",
					mknode("{}",
								mknode("",
										yyvsp[-5].node,
										mknode(")",
													mknode("EXPRESSION",
																			yyvsp[-1].node,
																			mknode(")",NULL,NULL)),
													NULL)),
								NULL),
					mknode(")",NULL,NULL));;
    break;}
case 86:
#line 398 "part1-1.y"
{yyval.node = mknode("IF-ELSE",
						mknode("EXPRESSION",
											yyvsp[-5].node,
											mknode("{}",
														mknode("",
																yyvsp[-2].node,
																mknode(")",NULL,NULL)),
														yyvsp[0].node)),
						mknode(")",NULL,NULL));;
    break;}
case 87:
#line 409 "part1-1.y"
{yyval.node=mknode("{}",
										mknode("",yyvsp[-1].node,NULL),
										mknode(")",NULL,NULL));;
    break;}
case 88:
#line 412 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 89:
#line 416 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 90:
#line 418 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,yyvsp[0].node);;
    break;}
case 91:
#line 419 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,yyvsp[0].node);;
    break;}
case 92:
#line 420 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,yyvsp[0].node);;
    break;}
case 93:
#line 421 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,yyvsp[0].node);;
    break;}
case 94:
#line 422 "part1-1.y"
{yyval.node=mknode("",yyvsp[-1].node,yyvsp[0].node);;
    break;}
case 95:
#line 423 "part1-1.y"
{yyval.node=mknode("{}",
      	   									mknode("",yyvsp[-2].node,yyvsp[0].node),
											mknode(")",NULL,NULL));;
    break;}
case 96:
#line 426 "part1-1.y"
{yyval.node=NULL;;
    break;}
case 97:
#line 429 "part1-1.y"
{yyval.node=mknode("",
										yyvsp[-2].node,
										mknode("RETURN_VAL",
															yyvsp[0].node,
															mknode(")",NULL,NULL)));;
    break;}
case 98:
#line 436 "part1-1.y"
{yyval.node=mknode("PRINT_TOKEN",mknode(yyvsp[0].string,NULL,NULL),NULL);;
    break;}
case 99:
#line 437 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 100:
#line 438 "part1-1.y"
{yyval.node=mknode("",yyvsp[0].node,NULL);;
    break;}
case 101:
#line 439 "part1-1.y"
{yyval.node=mknode("EXPRESSION",
											yyvsp[0].node,
											mknode(")",NULL,NULL));;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 445 "part1-1.y"



#include"lex.yy.c"


int main()
{
	return yyparse(); 
}

/* allocation for node*/
node* mknode (char *token, node *left, node *right)
{
	node *newnode = (node*)malloc(sizeof(node));
	newnode->left=left;
	newnode->right=right;
	newnode->token=token;
	return newnode;
}

void printSpace(int num){
	int i = 0;
	while (i < num)
		{
			printf(" ");
			i+=1;
		}
	/* char space = ' ';
	printf("%s",space*num); */
}
/* void printNodesTree(node* tree){
	if(tree != NULL){

	}
} */
void printTree(node* tree)
{	
	
	if (tree != NULL){
		if((strcmp(tree->token,"CODE") == 0 )        ||
		(strcmp(tree->token, "FUNC") == 0)        ||
		(strcmp(tree->token, "BODY") == 0)        ||
		(strcmp(tree->token, "ARGS") == 0)        ||
		(strcmp(tree->token, "{}") == 0)          ||
		(strcmp(tree->token, "RETURN_VAL") == 0)  || 
		(strcmp(tree->token, "CALL FUNC") == 0)   ||
		(strcmp(tree->token, "PARAMS") == 0)		 ||
		(strcmp(tree->token, "RET") == 0)		 ||
		(strcmp(tree->token,"DECLARATION") == 0 ) ||
		(strcmp(tree->token,"=") == 0)            ||
		(strcmp(tree->token,"FOR") == 0)		     ||
		(strcmp(tree->token,"WHILE") == 0)		 ||
		(strcmp(tree->token,"DO-WHILE") == 0)	 ||
		(strcmp(tree->token,"INIT") == 0)         ||
		(strcmp(tree->token,"EXPRESSION") == 0))
		{
			
			printSpace(spaces);
			
			if(strcmp(tree->token, "{}") == 0){

				printf("(BLOCK \n");
			}
			else if (strcmp(tree->token, "=") == 0){

				if(tree->left != NULL){
					printf("(%s %s\n",tree->token,tree->right->token);
				}
				else{

					printf("%s \n",tree->right->token);
					spaces -= 4;;
				}
			}
			else if(strcmp(tree->token,"OPERATION")){

				printf("(%s \n",tree->left->left->token);

			}
			else{

				printf("(%s \n",tree->token);
			}
			
			spaces += 4;
			printSpace(spaces);
			
		}

		else if (strcmp(tree->token, "PRINT_TOKEN") == 0)
		{

			printf("%s ",tree->left->token);
		}

		else if (strcmp(tree->token, "\n") == 0){
			printf("\n");
			printSpace(spaces);
		}

		else if ((strcmp(tree->token,"STR_VAL") == 0)    ||
			(strcmp(tree->token,"REAL_VAL") == 0)    ||
			(strcmp(tree->token,"CHAR_VAL") == 0)    ||
			(strcmp(tree->token,"DEC_VAL") == 0)     ||
			(strcmp(tree->token,"HEX_VAL") == 0)     ||
			(strcmp(tree->token,"BOOLVAL") == 0)    ||
			(strcmp(tree->token,"BOOL") == 0)        ||
			(strcmp(tree->token,"INT") == 0)         ||
			(strcmp(tree->token,"REAL") == 0)        ||
			(strcmp(tree->token,"STRING") == 0)      ||
			(strcmp(tree->token,"CHAR") == 0)        ||
			(strcmp(tree->token,"INTPTR") == 0)     ||
			(strcmp(tree->token,"CHARPTR") == 0)    ||
			(strcmp(tree->token,"REALPTR") == 0))
		{
			printf("%s",tree->token);
		}
		printTree(tree->left);
		printTree(tree->right);
	}
	else{
		printf("NO CODE TO PRESENT");
	}
	
	
}

int yyerror(char *e)
{
	int yydebug=1;
	fflush(stdout);
	fprintf(stderr,"Error %s at line %d\n" ,e,yylineno);
	fprintf(stderr, "does not accept '%s'\n",yytext);

	return 0;
} 


